"""Add ticket metadata fields

Revision ID: 2b57d8cefde0
Revises: a5e9eb0d513f
Create Date: 2025-12-12 16:55:47.575539

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2b57d8cefde0'
down_revision = 'c4b1e9d8f0e2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('ticket', schema=None) as batch_op:
        # Add with a server_default so SQLite can populate existing rows.
        batch_op.add_column(
            sa.Column(
                'status',
                sa.String(length=20),
                nullable=False,
                server_default=sa.text("'confirmed'")
            )
        )
        from sqlalchemy import inspect
        columns = [c['name'] for c in inspect(op.get_bind()).get_columns('ticket')]
        if 'booked_at' not in columns:
            batch_op.add_column(sa.Column('booked_at', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('ticket_pdf', sa.String(length=255), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('ticket', schema=None) as batch_op:
        batch_op.drop_column('ticket_pdf')
        batch_op.drop_column('booked_at')
        batch_op.drop_column('status')

    # ### end Alembic commands ###
