"""Add seat tracking fields to Ticket model and create TheatreSeat table

Revision ID: a5e9eb0d513f
Revises: f6f199068272
Create Date: 2025-12-12 03:05:05.137179

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a5e9eb0d513f'
down_revision = 'f6f199068272'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('theatre_seat',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('theatre_id', sa.Integer(), nullable=False),
    sa.Column('row_label', sa.String(length=10), nullable=False),
    sa.Column('seat_number', sa.Integer(), nullable=False),
    sa.Column('seat_type', sa.String(length=20), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['theatre_id'], ['theatre.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('theatre_id', 'row_label', 'seat_number', name='unique_theatre_seat')
    )
    with op.batch_alter_table('ticket', schema=None) as batch_op:
        batch_op.add_column(sa.Column('seat_row', sa.String(length=10), nullable=True))
        batch_op.add_column(sa.Column('seat_number', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('seat_id', sa.String(length=20), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('ticket', schema=None) as batch_op:
        batch_op.drop_column('seat_id')
        batch_op.drop_column('seat_number')
        batch_op.drop_column('seat_row')

    op.drop_table('theatre_seat')
    # ### end Alembic commands ###
