"""Add TMDB metadata fields to Show model

Revision ID: f6f199068272
Revises: 15abaca94a61
Create Date: 2025-12-11 17:27:44.057104

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f6f199068272'
down_revision = '15abaca94a61'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('show', schema=None) as batch_op:
        batch_op.add_column(sa.Column('tmdb_id', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('overview', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('runtime', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('release_date', sa.String(length=20), nullable=True))
        batch_op.add_column(sa.Column('tmdb_rating', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('backdrop', sa.String(length=255), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('show', schema=None) as batch_op:
        batch_op.drop_column('backdrop')
        batch_op.drop_column('tmdb_rating')
        batch_op.drop_column('release_date')
        batch_op.drop_column('runtime')
        batch_op.drop_column('overview')
        batch_op.drop_column('tmdb_id')

    # ### end Alembic commands ###
